version: '3.8'

services:
  web:
      container_name: web
      build: .
      restart: always
      ports:
        - 8080:8080
      volumes:
        - db-data:/etc/data


  mysqldb:
    container_name: userDB
    image: mysql
    environment:
      MYSQL_USER: "admin"
      MYSQL_ROOT_PASSWORD : "devenv22!"
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db-data:

