version: '3.8'

services:
  web:
      container_name: web
      build: .
      restart: always
      ports:
        - 8080:8080
      volumes:
        - web_data:/etc/data
      networks:
        - app-network

  mysqldb:
    container_name: userDB
    image: mysql
    environment:
      MYSQL_USER: "admin"
      MYSQL_ROOT_PASSWORD : "devenv22!"
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network

  webserver:
    image: nginx:mainline-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
        - "80:80"
        - "443:443"
    volumes:
        - web-root:/var/www/html
        - ./nginx-conf:/etc/nginx/conf.d
        - certbot-etc:/etc/letsencrypt
        - certbot-var:/var/lib/letsencrypt
        - dhparam:/etc/ssl/certs
    depends_on:
        - web
    networks:
        - app-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
        - certbot-etc:/etc/letsencrypt
        - certbot-var:/var/lib/letsencrypt
        - web-root:/var/www/html
    depends_on:
        - webserver
    command: certonly --webroot --webroot-path=/var/www/html --email ahhhfiq@gmail.com --agree-tos --no-eff-email --force-renewal -d ahhhfiq.com -d www.ahhhfiq.com



volumes:
  certbot-etc:
  certbot-var:
  web_data:
    name: ${VOLUME_WEB}
  db_data:
    name: ${VOLUME_DB}
  dhparam:
        driver: local
        driver_opts:
            type: none
            device: /home/ahhhfiq/INF2003/web/dhparam
            o: bind

networks:
    app-network:
        driver: bridge


