version: '3.8'

services:
  web:
      container_name: web
      build: .
      restart: always
      ports:
        - 8080:8080
      volumes:
        - web_data:/etc/data
      networks:
        - app-network

  mysqldb:
    container_name: userDB
    image: mysql
    environment:
      MYSQL_USER: "admin"
      MYSQL_ROOT_PASSWORD : "devenv22!"
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network

volumes:
  web_data:
    name: ${VOLUME_WEB}
  db_data:
    name: ${VOLUME_DB}

networks:
    app-network:
        driver: bridge


