FROM node:18

ARG NODE_ENV=development
ENV NODE_ENV=${NODE_ENV}

#Create Work Directory
WORKDIR /usr/src/trafficCam

#Copy package.json files
#To install app dependencies 
COPY package*.json ./


#Copy files
COPY . .

#Expose port
EXPOSE 8080

RUN npm install pm2 -g

RUN npm install

# RUN npm run seed

CMD bash -c "pm2-runtime app.js"
